@include('layouts.header')
@include('layouts.sidebar')
@include('admin.connect')

<!-- INVOICE FORM PAGE -->
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&family=Roboto:wght@300;400&display=swap" rel="stylesheet">

<div class="invoice-container">
    <h1 class="mb-3">Create Invoice</h1>

    @if(session('success'))
        <div class="alert alert-success">{{ session('success') }}</div>
    @endif
    @if($errors->any())
        <div class="alert alert-danger">
            <ul class="mb-0">
                @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form id="invoiceForm" method="POST" action="{{ route('invoices.store') }}">
        @csrf

        <!-- Client Selection -->
        <div class="mb-3">
            <label class="form-label">Select Client</label>
            <select name="client_id" class="form-select mb-2">
                <option value="">-- Choose a client --</option>
                @foreach($clients as $client)
                    <option value="{{ $client->id }}">
                        {{ $client->name }} @if($client->email) ({{ $client->email }}) @endif
                    </option>
                @endforeach
            </select>
        </div>

        <!-- Product Selection -->
        <div class="mb-3">
            <label class="form-label">Select Product</label>
            <select id="productSelect" class="form-select mb-2">
                <option value="">-- Choose a product --</option>
                @foreach($products as $product)
                    <option value="{{ $product->id }}" data-price="{{ $product->price }}">
                        {{ $product->name }} - Frw {{ number_format($product->price, 0) }}
                    </option>
                @endforeach
            </select>
            <button type="button" id="addProductBtn" class="btn btn-primary">
                Add to Invoice
            </button>
        </div>

        <!-- Invoice Items Table -->
        <div class="table-responsive">
            <table class="table table-bordered table-sm" id="invoiceTable">
                <thead class="table-light">
                    <tr>
                        <th>Description</th>
                        <th>Qty</th>
                        <th>Unit Price</th>
                        <th>Total</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>

        <!-- Totals -->
        <div class="d-flex justify-content-end mt-3">
            <div class="totals-box col-md-4">
                <div class="d-flex justify-content-between">
                    <span>Subtotal:</span><span id="subtotal">Frw 0</span>
                </div>
                <div class="d-flex justify-content-between">
                    <span>Tax:</span>
                    <input type="number" min="0" step="0.01" id="taxInput" class="form-control form-control-sm" placeholder="Enter Tax">
                </div>
                <div class="d-flex justify-content-between fw-bold mt-2">
                    <span>Grand Total:</span><span id="grandTotal">Frw 0</span>
                </div>
            </div>
        </div>

        <!-- Payment Method -->
        <div class="mb-3 mt-3">
            <label class="form-label">Payment Method</label>
            <select name="payment_method" id="paymentMethod" class="form-select">
                <option value="">-- Select Payment Method --</option>
                <option value="cash">Cash</option>
                <option value="mtn_momo">MTN MoMo</option>
                <option value="airtel_money">Airtel Money</option>
                <option value="card">Card</option>
                <option value="bank">Bank</option>
            </select>
        </div>

        <!-- Payment Interface Placeholder -->
        <div id="paymentInterface" class="mb-3"></div>

        <!-- Action Buttons -->
        <div class="mb-3 d-flex gap-2 flex-wrap">
            <button type="button" class="btn btn-primary" id="viewInvoiceBtn">View Current Invoice</button>
            <button type="submit" class="btn btn-success">Save Invoice & Process Payment</button>
        </div>
    </form>
</div>

<!-- INVOICE PREVIEW MODAL -->
<div id="invoicePreview">
    <div id="invoicePreviewContent">
        <span id="closePreview">&times;</span>
        <div class="invoice-header">
            <img src="{{ asset('images/logo.jpg') }}" alt="IVARA" style="height: 50px;">
            <h2>Invoice No....</h2>
        </div>
        <div id="previewBody"></div>
        <div class="footer">
            Digitally generated by IVARA. This invoice is valid for business use if only signed and stamped by IVARA department.
        </div>
        <button id="printInvoice" class="btn btn-success mt-3">Download / Print</button>
    </div>
</div>

<!-- STYLES -->
<style>
/* Invoice Container */
.invoice-container { width: 80%; margin-left: 270px; margin-top:45px; padding: 25px 35px; background-color: #ffffff; border-radius: 10px; box-shadow: 0 6px 20px rgba(0,0,0,0.08); font-family: 'Poppins', sans-serif;, Tahoma, Geneva, Verdana, sans-serif; color: #222; }
.invoice-container h1 { font-size: 28px; font-weight: 700; color: #0a0000ff; margin-bottom: 25px; }
.invoice-container .form-label { font-size: 15px; color: #444; font-weight: 600;margin-bottom: 6px;display: block;transition: color 0.3s ease, transform 0.3s ease; }
.invoice-container .form-label:hover {color: #924FC2;transform: translateX(3px);}
.invoice-container input:focus + .form-label,
.invoice-container select:focus + .form-label {color: #5f5c5c;font-weight: 700;}
.invoice-container select.form-select, .invoice-container input.form-control, .invoice-container input.form-control-sm { border-radius: 6px; border: 1.5px solid #ced4da; padding: 8px 12px; font-size: 14px; transition: border-color 0.3s; }
.invoice-container select.form-select:focus, .invoice-container input.form-control:focus, .invoice-container input.form-control-sm:focus { border-color: #5f5c5cff; box-shadow: 0 0 5px rgba(105,109,116,0.4); outline: none; }
.invoice-container .btn-primary { background-color: #924FC2; border-color: #C0C0C0; font-weight: 600; padding: 10px 20px; border-radius: 6px; transition: background-color 0.3s; }
.invoice-container .btn-primary:hover { background-color: #5f5c5cff; }
.invoice-container .btn-success { background-color: #924FC2; border-color: #924FC2; font-weight: 600; padding: 10px 20px; border-radius: 6px; transition: background-color 0.3s; }
.invoice-container .btn-success:hover { background-color: #924FC2; }
.invoice-container .btn-danger { background-color: #dc3545; border-color: #dc3545; font-weight: 600; padding: 8px 18px; border-radius: 6px; transition: background-color 0.3s; }
.invoice-container .btn-danger:hover { background-color: #b02a37; }

/* Table */
.table-responsive { overflow-x: auto; margin-top: 20px; border-radius: 6px; box-shadow: 0 3px 8px rgba(0,0,0,0.05); }
#invoiceTable { width: 100%; border-collapse: collapse; font-size: 14px; }
#invoiceTable th, #invoiceTable td { padding: 10px 12px; border-bottom: 1px solid #ddd; text-align: left; }
#invoiceTable thead tr { background-color: #e6f0ff; }
#invoiceTable th { font-weight: 600; color: #924FC2; }
#invoiceTable td { background-color: #fafafa; }
.totals-box { background-color: #f0f4ff; padding: 20px; border-radius: 10px; font-size: 15px; box-shadow: inset 0 0 8px rgba(45,108,223,0.1); }

/* Payment Cards */
.payment-card { display: flex; align-items: center; padding: 14px 20px; margin-top: 12px; border-radius: 12px; border: 1px solid #ddd; box-shadow: 0 6px 18px rgba(0,0,0,0.08); opacity: 5; transform: translateY(-20px); transition: all 0.5s ease; font-weight: 600; gap: 12px; color: #fff; }
.payment-card.show { opacity: 1; transform: translateY(0); }
.payment-card img { width: 40px; height: 40px; border-radius: 6px; background: #fff; padding: 3px; }
.payment-card input, .payment-card select { flex: 1; border-radius: 6px; padding: 6px 12px; border: 1px solid #fff; background-color: rgba(255,255,255,0.95); color: #000; }
.payment-card label { margin-right: 8px; min-width: 120px; }
/* ... Keep all other existing payment card styles as-is ... */

/* Invoice Preview */
#invoicePreview { display: none; position: fixed; top:0; left:0; width:100%; height:100%; background: rgba(0,0,0,0.6); z-index: 1000; overflow-y:auto; }
#invoicePreviewContent { background: #fff; margin: 30px auto; padding: 30px; width: 90%; max-width: 600px; border-radius: 8px; position: relative; font-size: 13px; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; box-shadow: 0 0 10px rgba(0,0,0,0.2); color: #333; }
#invoicePreviewContent .invoice-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
#invoicePreviewContent .invoice-header h2 { margin: 0; font-size: 20px; font-weight: 600; }
#invoicePreviewContent .address-section { display: flex; justify-content: space-between; margin-bottom: 20px; flex-wrap: wrap; }
#invoicePreviewContent .address-box, .address-method { width: 48%; padding: 15px; border-radius: 4px; font-size: 14px; box-sizing: border-box; margin-bottom: 10px; }
#invoicePreviewContent .address-box { background-color: #f8f9fa; }
.address-method { background-color: #5f5c5cff; color:#fff; }
#invoicePreviewContent table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 13px; }
#invoicePreviewContent table th { background-color: #5f5c5cff; color: #fff; text-align: left; padding: 8px; }
#invoicePreviewContent table td { padding: 8px; border-bottom: 1px solid #ddd; }
#invoicePreviewContent .totals { text-align: right; font-size: 14px; margin-top: 15px; }
#invoicePreviewContent .footer { font-size: 12px; color: #777; margin-top: 30px; text-align: center; border-top: 1px dashed #ccc; padding-top: 15px; }
#closePreview { position: absolute; top:10px; right:15px; font-size: 20px; cursor:pointer; }
@media print { #invoicePreviewContent { box-shadow: none !important; margin: 0 !important; width: auto !important; } .footer { page-break-after: always; } @page { margin: 0.5cm; } }
</style>

<!-- JS LOGIC -->
<script>
document.getElementById('paymentMethod').addEventListener('change', function(){
    const container = document.getElementById('paymentInterface');
    container.innerHTML = '';
    const val = this.value;
    const cards = [];

    if(val === 'cash'){
        cards.push(`<div class="payment-card cash"><img src="{{ asset('images/cash.png') }}" alt="Cash"><span>Cash Payment Selected</span></div>`);
    } else if(val === 'mtn_momo'){
        cards.push(`<div class="payment-card mtn"><img src="{{ asset('images/mtn.png') }}" alt="MTN MoMo"><label>MTN MoMo Number:</label><input type="text" name="mtn_number" placeholder="Enter MTN MoMo number"></div>`);
    } else if(val === 'airtel_money'){
        cards.push(`<div class="payment-card airtel"><img src="{{ asset('images/airtel.png') }}" alt="Airtel Money"><label>Airtel Number:</label><input type="text" name="airtel_number" placeholder="Enter Airtel Money number"></div>`);
    } else if(val === 'card'){
        cards.push(`<div class="payment-card card"><img src="{{ asset('images/card_no.png') }}" alt="Card"><label>Card Number:</label><input type="text" name="card_number" placeholder="Enter Card Number"></div>`);
        cards.push(`<div class="payment-card card"><img src="{{ asset('images/card_date.png') }}" alt="Expiry"><label>Expiry:</label><input type="month" name="card_expiry"></div>`);
        cards.push(`<div class="payment-card card"><img src="{{ asset('images/card_cvv.png') }}" alt="CVV"><label>CVV:</label><input type="text" name="card_cvv" placeholder="Enter CVV"></div>`);
    } else if(val === 'bank'){
        cards.push(`<div class="payment-card bank"><img src="{{ asset('images/bank.png') }}" alt="Bank"><label>Bank Name:</label><input type="text" name="bank_name" placeholder="Enter Bank Name"></div>`);
        cards.push(`<div class="payment-card bank"><img src="{{ asset('images/bank.png') }}" alt="Account"><label>Account Number:</label><input type="text" name="bank_account" placeholder="Enter Account Number"></div>`);
    }

    cards.forEach(html => {
        let div = document.createElement('div');
        div.innerHTML = html;
        container.appendChild(div.firstChild);
        setTimeout(() => div.firstChild.classList.add('show'), 50);
    });
});

// Add Product
document.getElementById('addProductBtn').addEventListener('click', function() {
    let select = document.getElementById('productSelect');
    let id = select.value;
    let name = select.options[select.selectedIndex].text;
    let price = parseFloat(select.options[select.selectedIndex].dataset.price);
    if(!id) return;
    let tbody = document.querySelector('#invoiceTable tbody');
    let row = document.createElement('tr');
    row.innerHTML = `<td>${name}<input type="hidden" name="products[]" value="${id}"></td>
        <td><input type="number" name="qty[]" value="1" min="1" class="form-control form-control-sm qty"></td>
        <td>Frw ${price.toFixed(0)}<input type="hidden" name="price[]" value="${price}"></td>
        <td class="total">Frw ${price.toFixed(0)}</td>
        <td><button type="button" class="btn btn-sm btn-danger removeBtn">X</button></td>`;
    tbody.appendChild(row);
    updateTotals();
});

// Update Totals
function updateTotals(){
    let subtotal = 0;
    document.querySelectorAll('#invoiceTable tbody tr').forEach(row=>{
        let qty = parseFloat(row.querySelector('.qty').value);
        let price = parseFloat(row.querySelector('input[name="price[]"]').value);
        let total = qty * price;
        row.querySelector('.total').innerText = `Frw ${total.toFixed(0)}`;
        subtotal += total;
    });

    let tax = parseFloat(document.getElementById('taxInput').value) || 0;
    let grand = subtotal + tax;

    document.getElementById('subtotal').innerText = `Frw ${subtotal.toFixed(0)}`;
    document.getElementById('grandTotal').innerText = `Frw ${grand.toFixed(0)}`;
}

// Quantity change, remove & tax input
document.addEventListener('input', e => { 
    if(e.target.classList.contains('qty') || e.target.id === 'taxInput') updateTotals(); 
});
document.addEventListener('click', e => { if(e.target.classList.contains('removeBtn')) { e.target.closest('tr').remove(); updateTotals(); } });

// Preview Invoice
document.getElementById('viewInvoiceBtn').addEventListener('click', function(){
    let client = document.querySelector('select[name="client_id"]').selectedOptions[0]?.text || 'N/A';
    let paymentMethod = document.querySelector('select[name="payment_method"]').selectedOptions[0]?.text || 'N/A';
    let rows = document.querySelectorAll('#invoiceTable tbody tr');
    if(rows.length === 0) { alert('Add products first'); return; }

    let html = `<div class="address-section">
            <div class="address-box"><strong>Bill To:</strong><br>${client}</div>
            <div class="address-box"><strong>Invoice Date:</strong><br>${new Date().toLocaleDateString()}</div>
            <div class="address-method"><strong>Payment Method:</strong><br>${paymentMethod}</div>
        </div>
        <table>
            <thead><tr><th>Description</th><th>Qty</th><th>Unit Price</th><th>Total</th></tr></thead>
            <tbody>`;
    rows.forEach(r => {
        let c = r.querySelectorAll('td');
        html += `<tr><td>${c[0].innerText}</td><td>${c[1].querySelector('input').value}</td><td>${c[2].innerText}</td><td>${c[3].innerText}</td></tr>`;
    });
    html += `</tbody></table>
        <div class="totals">
          <p><strong>Subtotal:</strong> ${document.getElementById('subtotal').innerText}</p>
          <p><strong>Tax:</strong> Frw ${parseFloat(document.getElementById('taxInput').value || 0).toFixed(0)}</p>
          <p><strong>Grand Total:</strong> ${document.getElementById('grandTotal').innerText}</p>
        </div>`;
    document.getElementById('previewBody').innerHTML = html;
    document.getElementById('invoicePreview').style.display = 'block';
});

// Close Modal
document.getElementById('closePreview').addEventListener('click', function(){ document.getElementById('invoicePreview').style.display = 'none'; });

// Print Invoice
document.getElementById('printInvoice').addEventListener('click', function(){
    let content = document.getElementById('invoicePreviewContent').innerHTML;
    let w = window.open('', '', 'height=600,width=800');
    w.document.write(`<html><head><title>Invoice</title><style>${document.querySelectorAll('style')[1].innerHTML}</style></head><body>` + content + `</body></html>`);
    w.document.close();
    w.focus();
    setTimeout(() => { w.print(); w.close(); }, 250);
});
</script>

@include('layouts.footer')
