<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Users Report</title>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #924FC2; padding-bottom: 10px; }
        .logo { max-width: 150px; margin-bottom: 10px; }
        h1 { color: #924FC2; font-size: 24px; margin: 0; }
        p { color: #666; font-size: 14px; margin: 5px 0; }
        
        table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 12px; }
        th { background-color: #924FC2; color: #fff; padding: 10px; text-align: left; }
        td { border-bottom: 1px solid #ddd; padding: 8px; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        
        .footer { position: fixed; bottom: 0; left: 0; right: 0; text-align: center; font-size: 11px; color: #aaa; padding: 10px; border-top: 1px solid #ddd; }
        .status-active { color: #00c853; font-weight: bold; }
        .status-inactive { color: #ff1744; font-weight: bold; }
    </style>
</head>
<body>

    <div class="header">
        <h1>IVARA Users Report</h1>
        <p>Report Period: {{ $startDate ?? 'All Time' }} to {{ $endDate ?? 'Present' }}</p>
        <p>Generated on: {{ date('F d, Y') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Username</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Role</th>
                <th>Status</th>
                <th>Joined</th>
            </tr>
        </thead>
        <tbody>
            @foreach($users as $user)
            <tr>
                <td>{{ $user->id }}</td>
                <td>{{ $user->name }}</td>
                <td>{{ $user->username }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->phone }}</td>
                <td>{{ $user->getRoleNames()->implode(', ') }}</td>
                <td><span class="{{ $user->status == 'active' ? 'status-active' : 'status-inactive' }}">{{ ucfirst($user->status) }}</span></td>
                <td>{{ $user->created_at->format('Y-m-d') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Confidential Report - Generated by IVARA System - Page <span class="pagenum"></span>
    </div>

</body>
</html>
